#!/bin/sh
#
#-	raster_clrs --
#-		Print a sequence of data boundaries and colors for
#-		raster plotting. See raster_clrs (1).
#
#	Requires hsv, bighi, biglo, bigsml, and biglrg applications.
#
#	Copyright (c) 2010 Gordon D. Carrie
#	All rights reserved.
#
#	$Revision: 1.3 $ $Date: 2011/09/02 20:19:30 $

# Determine format for data values, by default, or -f argument
fmt="%g"
if [ $1 = "-f" ]
then
    shift
    fmt=$1
    shift
fi

# Parse rest of command line
if [ $# -eq 3 ]
then
    # raster_clrs min max n_colors
    min=$1
    max=$2
    n_clr=$3
    step="uniform"
elif [ $# -eq 4 ]
then
    # raster_clrs min max n_colors step
    min=$1
    max=$2
    n_clr=$3
    step=$4
else
    echo "Usage: raster_clrs -f format min max n_colors [step]"
    exit 1
fi

# Angles on hue color wheel
h0=540
h1=300

# Create temporary files
app_nm=`basename $0`
btmp="/tmp/${app_nm}.$$.btmp"
ctmp="/tmp/${app_nm}.$$.ctmp"
trap "rm -f $btmp $ctmp" EXIT
trap "rm -f $btmp $ctmp" QUIT
trap "rm -f $btmp $ctmp" TERM
touch $btmp $ctmp

# Send data values to btmp file
case $step in
    (uniform) {
	awk -v min=$min -v max=$max -v n_clr=$n_clr -v fmt=$fmt \
		   'BEGIN {
		       fmt = fmt "\n"
			   s = (max - min) / n_clr
			   if ( max > min ) {
			       for (d = min; d <= max; d += s) {
				   printf fmt, d
			       }
			   }
		       if ( min > max ) {
			   for (d = min; d >= max; d += s) {
			       printf fmt, d
			   }
		       }
		   }' > $btmp
    }
    ;; 
    (biglo) {
	biglo $min $max ` expr $n_clr + 1` \
	    | awk -v fmt=$fmt'\n' '{printf fmt, $2}' > $btmp
    }
    ;;
    (bighi) {
	bighi $min $max ` expr $n_clr + 1` \
	    | awk -v fmt=$fmt'\n' '{printf fmt, $2}' > $btmp
    }
    ;;
    (bigsml) {
	bigsml $min $max ` expr $n_clr + 1` \
	    | awk -v fmt=$fmt'\n' '{printf fmt, $2}' > $btmp
    }
    ;;
    (biglrg) {
	biglrg $min $max ` expr $n_clr + 1` \
	    | awk -v fmt=$fmt'\n' '{printf fmt, $2}' > $btmp
    }
    ;;
    (*) {
	echo "$0: step must be one of biglo bighi bigsml biglrg"
	    exit 1
    }
esac

# Header
echo "raster $n_clr"

# Send color specifiers to ctmp file
hsv $h0 $h1 $n_clr | awk '{print $5}' > $ctmp

# Merge data values and color specifiers
paste $btmp $ctmp
