#!/bin/sh
#
#-	raster_clrs --
#-		Print a sequence of data boundaries and colors for
#-		raster plotting. See raster_clrs (1).
#
#	Requires hsv, bighi, biglo, and biglrg applications.
#
#	Copyright (c) 2010 Gordon D. Carrie
#	All rights reserved.
#
#	$Revision: 1.2 $ $Date: 2010/03/12 16:01:10 $

if [ $# -eq 3 ]
then
    # raster_clrs min max n_colors
    min=$1
    max=$2
    n_clr=$3
    step="uniform"
elif [ $# -eq 4 ]
then
    # raster_clrs min max n_colors step
    min=$1
    max=$2
    n_clr=$3
    step=$4
else
    echo "Usage: raster_clrs min max n_colors [step]"
    exit 1
fi

# Angles on hue color wheel
h0=540
h1=300

btmp="/tmp/$0.$$.btmp"
ctmp="/tmp/$0.$$.ctmp"
trap "rm -f $btmp $ctmp" EXIT
trap "rm -f $btmp $ctmp" QUIT
trap "rm -f $btmp $ctmp" TERM
touch $btmp $ctmp
case $step in
    (uniform) {
	bc > $btmp << END
	scale = 4
	s = ($max - $min) / $n_clr
	if ( $max > $min ) {
	    for (d = $min; d <= $max; d += s) {print d, "\n"}
	}
	if ( $min > $max ) {
	    for (d = $min; d >= $max; d += s) {print d, "\n"}
	}
END
    }
    ;; 
    (biglo) {
	biglo $min $max ` expr $n_clr + 1` | awk '{print $2}' > $btmp
    }
    ;;
    (bighi) {
	bighi $min $max ` expr $n_clr + 1` | awk '{print $2}' > $btmp
    }
    ;;
    (bigsml) {
	bigsml $min $max ` expr $n_clr + 1` | awk '{print $2}' > $btmp
    }
    ;;
    (biglrg) {
	biglrg $min $max ` expr $n_clr + 1` | awk '{print $2}' > $btmp
    }
    ;;
    (*) {
	echo "$0: step must be one of biglo bighi bigsml biglrg"
	exit 1
    }
esac
echo "raster $n_clr"
hsv $h0 $h1 $n_clr | awk '{print $5}' > $ctmp
paste $btmp $ctmp
